language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt

services:
  - postgresql

env:
  - DJANGO_VERSION=3.1

before_script:
  - psql -c "CREATE DATABASE purbeurre;" -U postgres
  - psql -c "CREATE USER django"
  - psql -c "ALTER USER django WITH PASSWORD 'django'"
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE purbeurre TO django"
  - psql -c "ALTER USER django CREATEDB;"

script:
  - python purbeurre_project\manage.py migrate
  - python purbeurre_project\manage.py test