# Generated by Django 3.1 on 2020-08-21 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200821_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='date_favorite',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date favori'),
            preserve_default=False,
        ),
    ]
