# Generated by Django 3.1 on 2020-08-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_favorite_date_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-date_favorite']},
        ),
    ]
