# Generated by Django 3.0.8 on 2020-07-26 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catprod',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
        migrations.AddField(
            model_name='catprod',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(through='products.CatProd', to='products.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('id_user', 'id_product')},
        ),
        migrations.AlterUniqueTogether(
            name='catprod',
            unique_together={('id_category', 'id_product')},
        ),
    ]
