# Generated by Django 3.0.8 on 2020-07-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200727_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fat_100g',
            field=models.FloatField(default=-1, verbose_name='Lipides'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_100g',
            field=models.FloatField(default=-1, verbose_name='Sel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='satured_fat_100g',
            field=models.FloatField(default=-1, verbose_name='Acides gras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugars_100g',
            field=models.FloatField(default=-1, verbose_name='Sucres'),
        ),
    ]
