# Generated by Django 3.0.8 on 2020-08-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200802_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.IntegerField(default=0, verbose_name='popularite'),
        ),
    ]
