# Generated by Django 3.1 on 2020-08-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name_fr',
            field=models.CharField(max_length=255, verbose_name='nom produit'),
        ),
    ]
